{
    "targets":[
        {
            "target_name":"addon",
            "sources":[
                "addon.cc",
                "my-object.h",
                "my-object.cc",
            ],
        }
    ]
}
